language: python
python:
- '2.7'
sudo: false
before_install:
- nvm install stable
install:
- pip install pygments cssselect html5lib lxml
- git clone --depth=100 --branch=master https://github.com/tabatkins/bikeshed.git
- pip install --editable ./bikeshed
- bikeshed update
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "4605f292f981"
  - COMMIT_AUTHOR_EMAIL: "rick@rbyers.net"
